build:
  image: reddit/reddit-py
  pull: true
  commands:
    - sudo apt-get update -q
    - sudo apt-get install -y puppet
    - sudo puppet apply puppet/manifests/init.pp --modulepath=puppet/modules
    - ulimit -q
    - sudo nosetests