branches:
    only:
        - master

sudo: required
dist: trusty

language: python
python:
    - "2.7"
    - "3.4"

virtualenv:
    system_site_packages: true

before_install:
    - sudo apt-get update -q
    - sudo apt-get install -y puppet

install:
    - sudo puppet apply puppet/manifests/init.pp --modulepath=puppet/modules
    - ulimit -q

script:
    - sudo nosetests
